services:
  timecentric-php:
    container_name: timecentric-php
    image: timecentric-php:dev
    labels:
      - "project=timecentric"
      - "service=php"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./dist:/var/www/html/dist
      - ./Console:/var/www/html/Console
      - ./guacamole:/var/www/html/guacamole
      - ./.env:/var/www/html/.env
    depends_on:
      - timecentric-db
    environment:
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
  timecentric-nginx:
    container_name: timecentric-nginx
    image: nginx:latest
    labels:
      - "project=timecentric"
      - "service=nginx"
    ports:
      - "${HTTPS_PORT:-8443}:443"
    volumes:
      - ./dist:/var/www/html/dist
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - timecentric-php
  timecentric-db:
    container_name: timecentric-db
    image: postgres:16
    labels:
      - "project=timecentric"
      - "service=database"
    environment:
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: