services:
  guacamole-php:
    container_name: guacamole-php
    image: guacamole-php:dev
    labels:
      - "project=guacamole"
      - "service=php"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./dist:/var/www/html/dist
    depends_on:
      - guacamole-db
    environment:
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
  guacamole-nginx:
    container_name: guacamole-nginx
    image: nginx:latest
    labels:
      - "project=guacamole"
      - "service=nginx"
    ports:
      - "${HTTPS_PORT:-8443}:443"
    volumes:
      - ./dist:/var/www/html/dist
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - guacamole-php
  guacamole-db:
    container_name: guacamole-db
    image: postgres:16
    labels:
      - "project=guacamole"
      - "service=database"
    environment:
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: